version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 568682978877.dkr.ecr.us-east-1.amazonaws.com
      - echo Building the application with Maven...
      - mvn clean package -DskipTests
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t academia-app/trabalho-de-conclusao-de-curso .
      - docker tag academia-app/trabalho-de-conclusao-de-curso:latest 568682978877.dkr.ecr.us-east-1.amazonaws.com/academia-app/trabalho-de-conclusao-de-curso:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 568682978877.dkr.ecr.us-east-1.amazonaws.com/academia-app/trabalho-de-conclusao-de-curso:latest
artifacts:
  files:
    - target/*.jar
