version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: academia-app
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_API_KEY=AIzaSyC-oMjWjUnG2YYYO5FMe7h4emfcgRa1oes
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:mysql://database-1.c61gygmoktsm.us-east-1.rds.amazonaws.com:3306/novotestecrud?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=tHKg4383zwUw
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    depends_on:
      redis:
        condition: service_started
    networks:
      - app-network

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

#  mysql:
#    image: mysql:8.0
#    container_name: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: senha123
#      MYSQL_DATABASE: novotestecrud
#    ports:
#      - "3306:3306"
#    networks:
#      - app-network
#    command: --default-authentication-plugin=mysql_native_password
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$MYSQL_ROOT_PASSWORD"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    volumes:
#       - mysql-data:/var/lib/mysql

networks:
  app-network:
    driver: bridge