
ALTER TABLE user_academia
ADD COLUMN role VARCHAR(50) NOT NULL;

ALTER TABLE user_admin
ADD COLUMN role VARCHAR(50) NOT NULL;

ALTER TABLE user_acad_admin
ADD COLUMN role VARCHAR(50) NOT NULL;

ALTER TABLE personais
ADD COLUMN role VARCHAR(50) NOT NULL;